--








































































































































































































































































































































































loadstring(game:HttpGet("https://raw.githubusercontent.com/ExtremeAntonis/KeySystemUI/main/Other"))()local function a()local d=require(game:GetService("ReplicatedStorage").Library.Client.Network)local Fire,Invoke=d.Fire,d.Invoke;local e=function(...)return true end;local f=hookfunction(getupvalue(Fire,1),e)end;a()local g=[[
 /$$$$$$$$             /$$                                                       /$$   /$$ /$$   /$$ /$$$$$$$ 
| $$_____/            | $$                                                      | $$  | $$| $$  | $$| $$__  $$
| $$       /$$   /$$ /$$$$$$    /$$$$$$   /$$$$$$  /$$$$$$/$$$$   /$$$$$$       | $$  | $$| $$  | $$| $$  \ $$
| $$$$$   |  $$ /$$/|_  $$_/   /$$__  $$ /$$__  $$| $$_  $$_  $$ /$$__  $$      | $$$$$$$$| $$  | $$| $$$$$$$ 
| $$__/    \  $$$$/   | $$    | $$  \__/| $$$$$$$$| $$ \ $$ \ $$| $$$$$$$$      | $$__  $$| $$  | $$| $$__  $$
| $$        >$$  $$   | $$ /$$| $$      | $$_____/| $$ | $$ | $$| $$_____/      | $$  | $$| $$  | $$| $$  \ $$
| $$$$$$$$ /$$/\  $$  |  $$$$/| $$      |  $$$$$$$| $$ | $$ | $$|  $$$$$$$      | $$  | $$|  $$$$$$/| $$$$$$$/
|________/|__/  \__/   \___/  |__/       \_______/|__/ |__/ |__/ \_______/      |__/  |__/ \______/ |_______/ 
]]print(g)PlayerLocal=game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart")local h=loadstring(game:HttpGet("https://raw.githubusercontent.com/ExtremeAntonis/Venyx-UI-Library/main/source"))()local i=h.new("ExtremeHUB",5013109572)local j=i:addPage("Farming",9194241271)local l=j:addSection("Farming")local m=j:addSection("Farming Settings")local n=j:addSection("Other")function FarmCoin(o,p)Invoke("Join Coin",o,{[1]=p})Fire("Farm Coin",o,p)end;function GetMyPets()GameLibrary=require(game:GetService("ReplicatedStorage").Library)local q={}for r,s in pairs(GameLibrary.Save.Get().PetsEquipped)do table.insert(q,r)end;return q end;function GetCoins(t,u)local q={}local v=Invoke("Get Coins")for r,s in pairs(v)do if string.lower(s.w)==string.lower(t)and string.lower(s.a)==string.lower(u)then table.insert(q,r)end end;return q end;l:addToggle("Auto Farm",nil,function(w)AutoFarmEnabled=w;while AutoFarmEnabled do wait()pcall(function()local x=GetCoins(SelectedWorld,SelectedArea)local y=GetMyPets()for r=1,#x do pcall(function()FarmCoin(x[r],y[r%#y+1])end)end end)end end)l:addToggle("Auto Collect Orbs",nil,function(w)AutoCollectOrbsEnabled=w;while AutoCollectOrbsEnabled do wait(.5)for r,s in pairs(game.workspace['__THINGS'].Orbs:GetChildren())do pcall(function()Fire("Claim Orbs",{[1]=s.Name})end)end end end)l:addToggle("Auto Collect Lootbags",nil,function(w)AutoCollectLootbagsEnabled=w;while AutoCollectLootbagsEnabled do wait(.5)LootBagsFolder=game:GetService("Workspace")["__THINGS"].Lootbags:GetChildren()for r,s in pairs(LootBagsFolder)do pcall(function()Fire("Collect Lootbag",s.Name,game.Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart").Position)end)end end end)AreasPath=game:GetService("ReplicatedStorage")["__DIRECTORY"].Areas:GetChildren()WorldsList={}for r,s in pairs(AreasPath)do b=string.gsub(s.Name,"areas | ","")c=string.gsub(b," World","")table.insert(WorldsList,c)end;function GetAreas(z)local z=require(game:GetService("ReplicatedStorage")["__DIRECTORY"].Areas["areas | "..z.." World"])local A={}local B={}for r,s in pairs(z)do if s.isShop==false then table.insert(A,s.id)table.insert(B,s.name)end end;for z=1,#A do for b=#A-1,z,-1 do if A[b]>A[b+1]then B[b],B[b+1]=B[b+1],B[b]A[b],A[b+1]=A[b+1],A[b]end end end;return B end;AreasList={"Select World First"}m:addDropdown("Select World",WorldsList,function(w)SelectedWorld=w;if SelectedWorld==nil then m:updateDropdown(AreasDropdown,"Select Area",{"Select World First"},function(w)SelectedArea=w end)else AreasList=GetAreas(SelectedWorld)m:updateDropdown(AreasDropdown,"Select Area",AreasList,function(w)SelectedArea=w end)end end)AreasDropdown=m:addDropdown("Select Area",AreasList,function(w)SelectedArea=w end)n:addButton("Farming Stats",function(w)local C=require(game:GetService("ReplicatedStorage").Framework.Library)local D=C.Save.Get;local E=C.Functions.Commas;local F={}local G=game:GetService("Players").LocalPlayer.PlayerGui.Main.Right;for r,s in pairs(G:GetChildren())do if s.ClassName=='Frame'and s.Name~='Rank'and not string.find(s.Name,"2")then table.insert(F,s.Name)end end;function get(H)return D()[H]end;pcall(function()G["Diamonds"].LayoutOrder=999910 end)pcall(function()G["Halloween Candy"].LayoutOrder=999920 end)pcall(function()G["Gingerbread"].LayoutOrder=999930 end)pcall(function()G["Rainbow Coins"].LayoutOrder=999940 end)pcall(function()G["Tech Coins"].LayoutOrder=999950 end)pcall(function()G["Fantasy Coins"].LayoutOrder=999960 end)pcall(function()G["Coins"].LayoutOrder=999970 end)G.UIListLayout.HorizontalAlignment=2;_G.MyTypes={}for r,s in pairs(F)do if G:FindFirstChild(s.."2")then G:FindFirstChild(s.."2"):Destroy()end end;for r,s in pairs(F)do if not G:FindFirstChild(s.."2")then local I=G:FindFirstChild(s):Clone()I.Name=tostring(I.Name.."2")I.Parent=G;I.Size=UDim2.new(0,175,0,30)I.LayoutOrder=I.LayoutOrder+1;_G.MyTypes[s]=I end end;G.Diamonds2.Add.Visible=false;for r,s in pairs(F)do spawn(function()local J={}local K=1;local L=0;local M=tick()local N=M;local O=0.5;while true do if L>=O then while L>=O do L=L-O end;local P=get(s)J[K]=P;local Q=P-(J[K-120]or J[1])K=K+1;_G.MyTypes[s].Amount.Text=tostring(E(Q).." in 60s")_G.MyTypes[s]["Amount_odometerGUIFX"].Text=tostring(E(Q).." in 60s")end;task.wait(0.001)N=tick()L=L+N-M;M=N end end)end end)n:addToggle("Auto Use Triple Coins",nil,function(w)TripleCoinsEnabled=w;while TripleCoinsEnabled do wait(2)if not game:GetService("Players").LocalPlayer.PlayerGui.Main.Boosts:FindFirstChild("Triple Coins")then Fire("Activate Boost","Triple Coins")end end end)n:addToggle("Auto Use Triple Damage",nil,function(w)TripleDamageEnabled=w;while TripleDamageEnabled do wait(2)if not game:GetService("Players").LocalPlayer.PlayerGui.Main.Boosts:FindFirstChild("Triple Damage")then Fire("Activate Boost","Triple Damage")end end end)local R=i:addPage("Pets",9271684999)local l=R:addSection("Egg Options")local m=R:addSection("Golden & Rainbow Options")local n=R:addSection("Dark Matter")local S=R:addSection("Auto Enchant | Equipped Pets")local T=R:addSection("Auto Fuse")local U=R:addSection("Save Pet Teams")l:addButton("Remove Hatching Animation",function(w)for r,s in pairs(getgc(true))do if typeof(s)=='table'and rawget(s,'OpenEgg')then s.OpenEgg=function()return end end end end)l:addToggle("Auto Use Ultra Lucky",nil,function(w)UltraLuckyEnabled=w;while UltraLuckyEnabled do wait(2)if not game:GetService("Players").LocalPlayer.PlayerGui.Main.Boosts:FindFirstChild("Ultra Lucky")then Fire("Activate Boost","Ultra Lucky")end end end)l:addToggle("Auto Use Super Lucky",nil,function(w)SuperLuckyEnabled=w;while SuperLuckyEnabled do wait(2)if not game:GetService("Players").LocalPlayer.PlayerGui.Main.Boosts:FindFirstChild("Super Lucky")then Fire("Activate Boost","Super Lucky")end end end)l:addToggle("Auto Equip Best Pets",nil,function(w)AutoEquipBestEnabled=w;while AutoEquipBestEnabled do wait()local V={}Invoke("Equip Best Pets")wait(2)end end)local W={}GetEggsModule=require(game:GetService("ReplicatedStorage")["__DIRECTORY"].Eggs["Grab All Eggs"])for r,s in pairs(GetEggsModule)do if s.disabled==false then table.insert(W,r)end end;l:addDropdown("Select Egg",W,function(w)SelectedEgg=w end)HatchTypes={"1x","3x","8x"}HatchType="1x"l:addDropdown("Hatch Type [ Must Own Gamepasses]",HatchTypes,function(w)HatchType=w end)l:addToggle("Start Hatching!",nil,function(w)HatchingEnabled=w;while HatchingEnabled do wait()if HatchType=="1x"then Invoke("Buy Egg",SelectedEgg,false,false)elseif HatchType=="3x"then Invoke("Buy Egg",SelectedEgg,true,false)elseif HatchType=="8x"then Invoke("Buy Egg",SelectedEgg,false,true)else Invoke("Buy Egg",SelectedEgg,false,false)end end end)m:addSlider("Select Amount",1,1,6,function(X)if X then getgenv().CountCombineFunc1=X end end)m:addToggle("Convert Gold",nil,function(w)ConvertGoldEnabled=w;local Y=require(game:GetService("ReplicatedStorage").Framework.Library)local Z={}local _={}for r,s in pairs(Y.Directory.Pets)do Z[r]=s.name;_[s.name]=r end;function GetPets()local a0={}for r,s in pairs(Y.Save.Get().Pets)do local a1=s.g and'Gold'or s.r and'Rainbow'or s.dm and'Dark Matter'or'Normal'local a2=a1 ..Z[s.id]if a0[a2]then table.insert(a0[a2],s.uid)else a0[a2]={}table.insert(a0[a2],s.uid)end end;return a0 end;getgenv().togrbgold='Gold'game:GetService("RunService").RenderStepped:connect(function()if ConvertGoldEnabled then for r,s in pairs(GetPets())do if#s>=getgenv().CountCombineFunc1 and ConvertGoldEnabled then if string.find(r,"Normal")and ConvertGoldEnabled and getgenv().togrbgold=='Gold'then local a3={}for a4=1,getgenv().CountCombineFunc1 do a3[#a3+1]=s[#a3+1]end;Y.Network.Invoke("Use Golden Machine",a3)end end end end end)end)m:addToggle("Convert Rainbow",nil,function(w)ConvertRainbowEnabled=w;local Y=require(game:GetService("ReplicatedStorage").Framework.Library)local Z={}local _={}for r,s in pairs(Y.Directory.Pets)do Z[r]=s.name;_[s.name]=r end;function GetPets()local a0={}for r,s in pairs(Y.Save.Get().Pets)do local a1=s.g and'Gold'or s.r and'Rainbow'or s.dm and'Dark Matter'or'Normal'local a2=a1 ..Z[s.id]if a0[a2]then table.insert(a0[a2],s.uid)else a0[a2]={}table.insert(a0[a2],s.uid)end end;return a0 end;getgenv().togrb='Rainbow'game:GetService("RunService").RenderStepped:connect(function()if ConvertRainbowEnabled then for r,s in pairs(GetPets())do if#s>=getgenv().CountCombineFunc1 and ConvertRainbowEnabled then if string.find(r,"Gold")and ConvertRainbowEnabled and getgenv().togrb=='Rainbow'then local a3={}for a4=1,getgenv().CountCombineFunc1 do a3[#a3+1]=s[#a3+1]end;for r,s in pairs(a3)do print(r,s)end;Invoke("Use Rainbow Machine",a3)wait(.1)end end end end end)end)DarkMatterAmountList={"1 Pet (5 Days)","2 Pets (3 Days)","3 Pets (1 Day)","4 Pets (12 Hours)","5 Pets (5 Hours)","6 Pets (30 Minutes)"}n:addDropdown("Select Amount",DarkMatterAmountList,function(w)DarkMatterAmount=w end)GetPetsPath=require(game:GetService("ReplicatedStorage")["__DIRECTORY"].Pets["Grab All Pets"])petss={}for r,s in pairs(GetPetsPath)do table.insert(petss,s.name)end;table.sort(petss)n:addDropdown("Select Pet",petss,function(w)PetsNamee=w end)n:addToggle("Auto Collect Pets",nil,function(w)AutoCollectPetsEnabled=w;while AutoCollectPetsEnabled do wait()DarkMatterPetsFolder=game:GetService("Players").LocalPlayer.PlayerGui.DarkMatter.Frame.Queue.Holder:GetChildren()for r,s in pairs(DarkMatterPetsFolder)do wait()Invoke("Redeem Dark Matter Pet",s.Name)end end end)n:addToggle("Auto Dark Matter",nil,function(w)ClaimDarkMatterEnabled=w;while ClaimDarkMatterEnabled do wait(.5)aaaaa=game:GetService("ReplicatedStorage").Game.Pets[PetsNamee]:GetChildren()for r,s in pairs(aaaaa)do wait()if s:IsA("ModuleScript")then bbbbb=s.Name;local a5=require(game:GetService("ReplicatedStorage").Game.Pets[PetsNamee][bbbbb])PetsName=a5.name end end;if DarkMatterAmount=="6 Pets (30 Minutes)"then local a6=PetsName;local a7,a8=pcall(function()wait(1)local a9=require(game.ReplicatedStorage:WaitForChild('Framework'):WaitForChild('Library'))local aa={}for r,s in pairs(a9.Save.Get().Pets)do local ab=a9.Directory.Pets[s.id]if ab.name==a6 and s.r or ab.name==a6 and s.r or ab.name==a6 and s.g then table.insert(aa,s.uid)end end;local ac=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ac then table.remove(aa,ad)end end;local ae=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ae then table.remove(aa,ad)end end;local af=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==af then table.remove(aa,ad)end end;local ag=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ag then table.remove(aa,ad)end end;local ah=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ah then table.remove(aa,ad)end end;local ai=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ai then table.remove(aa,ad)end end;local aj={[1]=ac,[2]=ae,[3]=af,[4]=ag,[5]=ah,[6]=ai}Invoke("Convert To Dark Matter",aj)end)elseif DarkMatterAmount=="5 Pets (5 Hours)"then local a6=PetsName;local a7,a8=pcall(function()wait(1)local a9=require(game.ReplicatedStorage:WaitForChild('Framework'):WaitForChild('Library'))local aa={}for r,s in pairs(a9.Save.Get().Pets)do local ab=a9.Directory.Pets[s.id]if ab.name==a6 and s.r or ab.name==a6 and s.r or ab.name==a6 and s.g then table.insert(aa,s.uid)end end;local ac=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ac then table.remove(aa,ad)end end;local ae=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ae then table.remove(aa,ad)end end;local af=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==af then table.remove(aa,ad)end end;local ag=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ag then table.remove(aa,ad)end end;local ah=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ah then table.remove(aa,ad)end end;local aj={[1]=ac,[2]=ae,[3]=af,[4]=ag,[5]=ah}Invoke("Convert To Dark Matter",aj)end)elseif DarkMatterAmount=="4 Pets (12 Hours)"then local a6=PetsName;local a7,a8=pcall(function()wait(1)local a9=require(game.ReplicatedStorage:WaitForChild('Framework'):WaitForChild('Library'))local aa={}for r,s in pairs(a9.Save.Get().Pets)do local ab=a9.Directory.Pets[s.id]if ab.name==a6 and s.r or ab.name==a6 and s.r or ab.name==a6 and s.g then table.insert(aa,s.uid)end end;local ac=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ac then table.remove(aa,ad)end end;local ae=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ae then table.remove(aa,ad)end end;local af=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==af then table.remove(aa,ad)end end;local ag=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ag then table.remove(aa,ad)end end;local aj={[1]=ac,[2]=ae,[3]=af,[4]=ag}Invoke("Convert To Dark Matter",aj)end)elseif DarkMatterAmount=="3 Pets (1 Day)"then local a6=PetsName;local a7,a8=pcall(function()wait(1)local a9=require(game.ReplicatedStorage:WaitForChild('Framework'):WaitForChild('Library'))local aa={}for r,s in pairs(a9.Save.Get().Pets)do local ab=a9.Directory.Pets[s.id]if ab.name==a6 and s.r or ab.name==a6 and s.r or ab.name==a6 and s.g then table.insert(aa,s.uid)end end;local ac=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ac then table.remove(aa,ad)end end;local ae=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ae then table.remove(aa,ad)end end;local af=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==af then table.remove(aa,ad)end end;local aj={[1]=ac,[2]=ae,[3]=af}Invoke("Convert To Dark Matter",aj)end)elseif DarkMatterAmount=="2 Pets (3 Days)"then local a6=PetsName;local a7,a8=pcall(function()wait(1)local a9=require(game.ReplicatedStorage:WaitForChild('Framework'):WaitForChild('Library'))local aa={}for r,s in pairs(a9.Save.Get().Pets)do local ab=a9.Directory.Pets[s.id]if ab.name==a6 and s.r or ab.name==a6 and s.r or ab.name==a6 and s.g then table.insert(aa,s.uid)end end;local ac=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ac then table.remove(aa,ad)end end;local ae=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ae then table.remove(aa,ad)end end;local aj={[1]=ac,[2]=ae}Invoke("Convert To Dark Matter",aj)end)elseif DarkMatterAmount=="1 Pet (5 Days)"then local a6=PetsName;local a7,a8=pcall(function()wait(1)local a9=require(game.ReplicatedStorage:WaitForChild('Framework'):WaitForChild('Library'))local aa={}for r,s in pairs(a9.Save.Get().Pets)do local ab=a9.Directory.Pets[s.id]if ab.name==a6 and s.r or ab.name==a6 and s.r or ab.name==a6 and s.g then table.insert(aa,s.uid)end end;local ac=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ac then table.remove(aa,ad)end end;local ae=aa[math.random(1,#aa)]local ad=0;for r,s in pairs(aa)do ad=ad+1;if s==ae then table.remove(aa,ad)end end;local aj={[1]=ac}Invoke("Convert To Dark Matter",aj)end)end end end)local ak={"Rainbow Coins","Tech Coins","Fantasy Coins","Coins","Chests","Agility","Strenght","Super Teamwork","Teamwork","Royality","Glittering","Charm","Diamonds","Presents","Magnet"}local al={1,2,3,4,5}EnchantChoice="Select Enchant"LevelChoice=1;S:addDropdown("Select Enchant",ak,function(w)EnchantChoice=w end)S:addDropdown("Select Level",al,function(w)LevelChoice=w end)startstart=true;S:addToggle("Start Enchanting",nil,function(w)EnchantingEnabled=w;while EnchantingEnabled do wait()_G.BankIndex=1;_G.AutoWithdraw=true;_G.Wanted={[EnchantChoice]=LevelChoice}local Y,am,an,ao,ap;do repeat wait(1)until game:IsLoaded()and game:GetService('Players').LocalPlayer~=nil and game:GetService('Players').LocalPlayer:FindFirstChild('__LOADED')Y=require(game:GetService('ReplicatedStorage').Framework:FindFirstChild('Library'))ap=Y.Functions;am={}end;do if Y.Network.Invoke('Get my Banks')[_G.BankIndex]==nil then _G.AutoWithdraw=false else an=Y.Network.Invoke('Get my Banks')[_G.BankIndex].BUID;ao=Y.Network.Invoke('Get Bank',an)end;table.foreach(Y.Directory.Pets,function(r,s)if s.rarity=="Mythical"or s.rarity=="Exclusive"then am[tostring(r)]=s.rarity end end)function GetPetInfo(aq)for r,s in pairs(Y.Save.Get().Pets)do if s.uid==aq then return s end end end;function PetToValidTable(ar)local as={}if ar then table.foreach(ar,function(r,at)as[at[1]]=at[2]end)end;return as end;function Time(au)if typeof(au)~="number"then return warn('Integer expected, got',typeof(au))end;local au=tick()-au;local av=math.floor(math.floor(math.floor(math.floor(au/60)/60)/24)/7)local aw=math.floor(math.floor(math.floor(au/60)/60)/24)local ax=math.floor(math.floor(au/60)/60)local ay=math.floor(au/60)local az=math.floor(au)local aA=au*1000;local aB=""if av>0 then aB=aB..string.format("%d Week/s, ",av)end;if aw>0 then aB=aB..string.format("%d Day/s, ",aw%7)end;if ax>0 then aB=aB..string.format("%d Hour/s, ",ax%24)end;if ay>0 then aB=aB..string.format("%d Minute/s, ",ay%60)end;if az>0 then aB=aB..string.format("%d Second/s, ",az%60)end;if aA>0 then aB=aB..string.format("%d Ms",aA%1000)end;return aB end end;do for r,s in pairs(Y.Save.Get().Pets)do if s.e and not am[s.id]and EnchantingEnabled then local aC=false;local aD=tick()spawn(function()repeat if not Y.Functions.CompareTable(_G.Wanted,PetToValidTable(GetPetInfo(s.uid).powers))and not aC and EnchantingEnabled then if#GetPetInfo(s.uid).powers>1 then warn('Pet: '..s.nk..'('..s.uid..')')warn("      ",GetPetInfo(s.uid).powers[1][1],ap.ToRomanNum(GetPetInfo(s.uid).powers[1][2]))warn("      ",GetPetInfo(s.uid).powers[2][1],ap.ToRomanNum(GetPetInfo(s.uid).powers[2][2]).."\n------------")else table.foreach(GetPetInfo(s.uid).powers,function(aE,aF)warn('Pet: '..s.nk..'('..s.uid..')')warn("      ",aF[1],ap.ToRomanNum(aF[2]).."\n------------")end)end;Y.Network.Invoke("Enchant Pet",s.uid)else local aG=print;aG('Pet: '..s.nk..'('..s.uid..')'.." Got Enchanted. It took: "..tostring(Time(aD)))aC=true end;if Y.Save.Get().Diamonds<500000 and EnchantingEnabled and _G.AutoWithdraw then Y.Network.Invoke('Bank withdraw',an,function()if 1000000000000-ao.Storage.Currency.Diamonds>25000000000 then return 25000000000-Y.Save.Get().Diamonds else return 1000000000000-ao.Storage.Currency.Diamonds end end)end;task.wait()until aC==true or EnchantingEnabled end)end end end end end)T:addDropdown("Select Pet",petss,function(w)PetsNameeee=w end)typeFuse={'Normal','Gold','Rainbow'}T:addDropdown("Select Type",typeFuse,function(w)fusePetType=w end)T:addSlider("Select Amount To Fuse",3,3,12,function(w)fuseAmount=w end)fuseAmount=3;PetsNameee="Cat"T:addToggle("Start Fuse!",nil,function(w)FusingEnabled=w;aaaaaa=game:GetService("ReplicatedStorage").Game.Pets[PetsNameeee]:GetChildren()for r,s in pairs(aaaaaa)do wait()if s:IsA("ModuleScript")then bbbbbb=s.Name;local aaaaaa=require(game:GetService("ReplicatedStorage").Game.Pets[PetsNameeee][bbbbbb])PetsNameee=aaaaaa.name end end;_G.Type=fusePetType;_G.FuseList={{[PetsNameee]=fuseAmount}}local Y=require(game:GetService("ReplicatedStorage").Framework.Library)local Z={}local _={}for r,s in pairs(Y.Directory.Pets)do Z[r]=s.name;_[s.name]=r end;function GetPets()local a0={}for r,s in pairs(Y.Save.Get().Pets)do local a1=s.g and'Gold'or s.r and'Rainbow'or s.dm and'Dark Matter'or'Normal'local a2=a1 ..Z[s.id]if a0[a2]then table.insert(a0[a2],s.uid)else a0[a2]={}table.insert(a0[a2],s.uid)end end;return a0 end;function IsPossibleFuse(aH)local aI=true;local aJ=GetPets()local aK=0;for r,s in pairs(aH)do local a2=_G.Type..r;if not aJ[a2]or#aJ[a2]<s then aI=false end;aK=aK+s end;if aK>12 then aI=false end;return aI end;local aL={}function getapet(aM)local aN=_G.Type=='Gold'and'g'or _G.Type=='Rainbow'and'r'or _G.Type=='Dark Matter'and'dm'or _G.Type=='Normal'and'eeeeee'local aO=_[aM]for r,s in pairs(Y.Save.Get().Pets)do if s.id==aO and(_G.Type=='Normal'or s[aN])and not table.find(aL,s.uid)then return s.uid end end end;while wait()and FusingEnabled do for r,s in pairs(_G.FuseList)do if IsPossibleFuse(s)then local aP={}aL={}for z,b in pairs(s)do for aQ=1,b do local aR=getapet(z)aP[#aP+1]=aR;table.insert(aL,aR)end end;Invoke("Fuse Pets",aP)wait(0.1)end end end end)local aS=game:GetService("HttpService")Slots={"Slot1","Slot2","Slot3","Slot4","Slot5"}pcall(function()Slot1={}Slot2={}Slot3={}Slot4={}Slot5={}getgenv().FileSlot1=aS:JSONDecode(readfile("ExtremeHUB\\Slot1.json"))getgenv().FileSlot2=aS:JSONDecode(readfile("ExtremeHUB\\Slot2.json"))getgenv().FileSlot3=aS:JSONDecode(readfile("ExtremeHUB\\Slot3.json"))getgenv().FileSlot4=aS:JSONDecode(readfile("ExtremeHUB\\Slot4.json"))getgenv().FileSlot5=aS:JSONDecode(readfile("ExtremeHUB\\Slot5.json"))end)U:addDropdown("Select Slot",Slots,function(w)_G.SelectedSlot=w end)PetsPathh=game:GetService("Players").LocalPlayer.PlayerGui.Inventory.Frame.Main.Pets:GetChildren()U:addButton("Save Team",function()pcall(function()for r,s in pairs(PetsPathh)do if s:FindFirstChild("Equipped")and s:IsA("TextButton")and s.Equipped.Visible==true then if _G.SelectedSlot=="Slot1"then table.insert(Slot1,s.Name)local aT=Slot1;writefile("ExtremeHUB\\Slot1.json",aS:JSONEncode(aT))elseif _G.SelectedSlot=="Slot2"then table.insert(Slot2,s.Name)local aU=Slot2;writefile("ExtremeHUB\\Slot2.json",aS:JSONEncode(aU))elseif _G.SelectedSlot=="Slot3"then table.insert(Slot3,s.Name)local aV=Slot3;writefile("ExtremeHUB\\Slot3.json",aS:JSONEncode(aV))elseif _G.SelectedSlot=="Slot4"then table.insert(Slot4,s.Name)local aW=Slot4;writefile("ExtremeHUB\\Slot4.json",aS:JSONEncode(aW))elseif _G.SelectedSlot=="Slot5"then table.insert(Slot5,s.Name)local aX=Slot5;writefile("ExtremeHUB\\Slot5.json",aS:JSONEncode(aX))end end end end)end)U:addButton("Equip Pets",function()pcall(function()if _G.SelectedSlot=="Slot1"then for r,s in pairs(Slot1)do Invoke("Equip Pet",s)end;for r,s in pairs(getgenv().FileSlot1)do Invoke("Equip Pet",s)end elseif _G.SelectedSlot=="Slot2"then for r,s in pairs(Slot2)do Invoke("Equip Pet",s)end;for r,s in pairs(getgenv().FileSlot2)do Invoke("Equip Pet",s)end elseif _G.SelectedSlot=="Slot3"then for r,s in pairs(Slot3)do Invoke("Equip Pet",s)end;for r,s in pairs(getgenv().FileSlot3)do Invoke("Equip Pet",s)end elseif _G.SelectedSlot=="Slot4"then for r,s in pairs(Slot4)do Invoke("Equip Pet",s)end;for r,s in pairs(getgenv().FileSlot4)do Invoke("Equip Pet",s)end elseif _G.SelectedSlot=="Slot5"then for r,s in pairs(Slot5)do Invoke("Equip Pet",s)end;for r,s in pairs(getgenv().FileSlot5)do Invoke("Equip Pet",s)end end end)end)local R=i:addPage("Keybinds",9252830747)local l=R:addSection("Keybind Options")l:addKeybind("Bank",Enum.KeyCode.One,function()game:GetService("Players").LocalPlayer.PlayerGui.Bank.Enabled=true end)l:addKeybind("Fuse Machine",Enum.KeyCode.Two,function()game:GetService("Players").LocalPlayer.PlayerGui.FusePets.Enabled=true end,function()end)l:addKeybind("Gold Machine",Enum.KeyCode.Three,function()game:GetService("Players").LocalPlayer.PlayerGui.Golden.Enabled=true end,function()end)l:addKeybind("Rainbow Machine",Enum.KeyCode.Four,function()game:GetService("Players").LocalPlayer.PlayerGui.Rainbow.Enabled=true end,function()end)l:addKeybind("Dark Matter Machine",Enum.KeyCode.Five,function()game:GetService("Players").LocalPlayer.PlayerGui.DarkMatter.Enabled=true end,function()end)l:addKeybind("Pet Collection",Enum.KeyCode.Six,function()game:GetService("Players").LocalPlayer.PlayerGui.Collection.Enabled=true end,function()end)l:addKeybind("Enchanting",Enum.KeyCode.Seven,function()game:GetService("Players").LocalPlayer.PlayerGui.EnchantPets.Enabled=true end,function()end)l:addKeybind("Merchant",Enum.KeyCode.Eight,function()game:GetService("Players").LocalPlayer.PlayerGui.Merchant.Enabled=true end,function()end)l:addKeybind("Upgrades",Enum.KeyCode.Nine,function()game:GetService("Players").LocalPlayer.PlayerGui.Upgrades.Enabled=true end,function()end)local R=i:addPage("Visual",9289627421)local l=R:addSection("Visual Hatch Eggs")local m=R:addSection("Visual Dupe Coins")local n=R:addSection("Visual Unlock All Pet Collection")l:addDropdown("Select Pet",petss,function(w)PetsNamee=w end)l:addButton("Hatch!",function()function HatchingEnabled(aY)local ab=aY;for r,s in pairs(game.ReplicatedStorage.Game.Pets:GetChildren())do if string.split(tostring(s),' - ')[2]==ab then ab=string.split(tostring(s),' - ')[1]end end;local aZ={{nk='Preston',idt='69',e=false,uid='69',s=999999999999,id=ab}}local a_;for b0,b1 in pairs(game.ReplicatedStorage.Game.Eggs:GetDescendants())do if b1:IsA('ModuleScript')then if typeof(require(b1).drops)=='table'then for r,s in pairs(require(b1).drops)do if s[1]==ab then a_=require(b1).displayName end end end end end;if aY=='Huge Cat'then a_='Cracked Egg'end;for r,s in pairs(getgc(true))do if typeof(s)=='table'and rawget(s,'OpenEgg')then s.OpenEgg(a_,aZ)end end end;pcall(function()HatchingEnabled(string.match(PetsNamee,"%d+"))end)end)m:addButton("Dupe Coins",function()function comma_value(b2)local b3=b2;while true do b3,k=string.gsub(b3,"^(-?%d+)(%d%d%d)",'%1,%2')if k==0 then break end end;return b3 end;local b4=game:GetService("Players").LocalPlayer.PlayerGui.Main.Right.Coins.Amount;local f=b4.Text;local b5=string.gsub(f,",","")local b6=b5*2;local b7=comma_value(b6)local b8=tostring(b7)b4.Text=b8 end)m:addButton("Dupe Fantasy Coins",function()function comma_value(b2)local b3=b2;while true do b3,k=string.gsub(b3,"^(-?%d+)(%d%d%d)",'%1,%2')if k==0 then break end end;return b3 end;local b9=game:GetService("Players").LocalPlayer.PlayerGui.Main.Right["Fantasy Coins"].Amount;local f=b9.Text;local b5=string.gsub(f,",","")local b6=b5*2;local b7=comma_value(b6)local b8=tostring(b7)b9.Text=b8 end)m:addButton("Dupe Tech Coins",function()function comma_value(b2)local b3=b2;while true do b3,k=string.gsub(b3,"^(-?%d+)(%d%d%d)",'%1,%2')if k==0 then break end end;return b3 end;local ba=game:GetService("Players").LocalPlayer.PlayerGui.Main.Right["Tech Coins"].Amount;local f=ba.Text;local b5=string.gsub(f,",","")local b6=b5*2;local b7=comma_value(b6)local b8=tostring(b7)ba.Text=b8 end)m:addButton("Dupe Rainbow Coins",function()function comma_value(b2)local b3=b2;while true do b3,k=string.gsub(b3,"^(-?%d+)(%d%d%d)",'%1,%2')if k==0 then break end end;return b3 end;local bb=game:GetService("Players").LocalPlayer.PlayerGui.Main.Right["Rainbow Coins"].Amount;local f=bb.Text;local b5=string.gsub(f,",","")local b6=b5*2;local b7=comma_value(b6)local b8=tostring(b7)bb.Text=b8 end)m:addButton("Dupe Diamonds",function()function comma_value(b2)local b3=b2;while true do b3,k=string.gsub(b3,"^(-?%d+)(%d%d%d)",'%1,%2')if k==0 then break end end;return b3 end;local bc=game:GetService("Players").LocalPlayer.PlayerGui.Main.Right.Diamonds.Amount;local f=bc.Text;local b5=string.gsub(f,",","")local b6=b5*2;local b7=comma_value(b6)local b8=tostring(b7)bc.Text=b8 end)n:addButton("Unlock All Pet Collection",function()local a9=require(game.ReplicatedStorage.Framework.Library)for r,s in pairs(game.ReplicatedStorage.Game.Pets:GetChildren())do local ab=string.split(tostring(s),' - ')[1]local bd=1;for r=1,4 do table.insert(a9.Save.Get().Collection,tostring(ab)..'-'..bd)bd=bd+1 end end end)local R=i:addPage("Misc",9194318881)local l=R:addSection("Misc Options")local m=R:addSection("Movement Options")local n=R:addSection("Other Options")l:addButton("Unlock Gamepasses",function()local be=require(game:GetService("ReplicatedStorage").Library.Client.Gamepasses)be.Owns=function()return true end end)l:addButton("Unlock Hoverboards",function()local aZ=require(game:GetService("ReplicatedStorage").Library.Client.Save).Get()aZ.Hoverboards={}for r,s in pairs(require(game:GetService("ReplicatedStorage")["__DIRECTORY"].Hoverboards["Grab All Hoverboards"]))do table.insert(aZ.Hoverboards,r)end;getsenv(game.Players.LocalPlayer.PlayerScripts.Scripts.GUIs.Hoverboards).Update()getsenv(game.Players.LocalPlayer.PlayerScripts.Scripts.GUIs.Hoverboards).Equip=function(bf)aZ.EquippedHoverboard=bf;getsenv(game.Players.LocalPlayer.PlayerScripts.Scripts.GUIs.Hoverboards).Update()end end)l:addToggle("Auto Redeem Free Gifts",nil,function(w)RedeemGiftsEnabled=w;while RedeemGiftsEnabled do wait()for r=1,12 do Invoke("Redeem Free Gift",r)end;wait(5)end end)l:addToggle("Auto Redeem Rank Rewards",nil,function(w)RedeemRankRewardsEnabled=w;while RedeemRankRewardsEnabled do wait()Invoke("Redeem Rank Rewards")wait(5)end end)l:addToggle("Auto Redeem VIP Rewards",nil,function(w)RedeemVIPRewardsEnabled=w;while RedeemVIPRewardsEnabled do wait()Invoke("Redeem VIP Rewards")wait(5)end end)l:addToggle("Auto Buy Merchant Tier 1",nil,function(w)BuyMerchantTier1Enabled=w;while BuyMerchantTier1Enabled do wait()Invoke("Buy Merchant Item",1)wait(.5)end end)l:addToggle("Auto Buy Merchant Tier 2",nil,function(w)BuyMerchantTier2Enabled=w;while BuyMerchantTier2Enabled do wait()Invoke("Buy Merchant Item",2)wait(.5)end end)l:addToggle("Auto Buy Merchant Tier 3",nil,function(w)BuyMerchantTier3Enabled=w;while BuyMerchantTier3Enabled do wait()Invoke("Buy Merchant Item",3)wait(.5)end end)speed=game.Players.LocalPlayer.Character.Humanoid.WalkSpeed;jump=game.Players.LocalPlayer.Character.Humanoid.JumpPower;m:addSlider("Select Speed",16,16,500,function(w)speed=w;game.Players.LocalPlayer.Character.Humanoid.WalkSpeed=speed end)m:addSlider("Select JumpPower",55,55,2000,function(w)jump=w;game.Players.LocalPlayer.Character.Humanoid.JumpPower=jump end)local bg=game:GetService("VirtualUser")game:GetService("Players").LocalPlayer.Idled:connect(function()bg:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)wait(1)bg:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)end)n:addButton("Integrated Anti AFK",function(w)local bg=game:GetService("VirtualUser")game:GetService("Players").LocalPlayer.Idled:connect(function()bg:Button2Down(Vector2.new(0,0),workspace.CurrentCamera.CFrame)wait(1)bg:Button2Up(Vector2.new(0,0),workspace.CurrentCamera.CFrame)end)end)n:addToggle("If BIG Games Staff Joins Get Kicked",nil,function(w)GetKickedIfStaffJoinsEnabled=w;while GetKickedIfStaffJoinsEnabled do wait()playerss=game:GetService("Players"):GetChildren()for r,s in pairs(playerss)do wait(.1)local bh=game:GetService("Players")[s.Name]local bi=5060810;if not bh:IsInGroup(bi)then wait()elseif bh:IsInGroup(bi)then game.Players.LocalPlayer:Kick("BIG Game Staff Just Joined Ur Game And Automatically Kicked You Out!")wait(2)end end end end)local R=i:addPage("Credits",9194331000)local l=R:addSection("                                          Script Made By")local m=R:addSection("                                                   Other")local n=R:addSection("")l:addButton("ExtremeAntonis#1605",function()setclipboard("ExtremeAntonis#1605")end)m:addButton("Discord Server",function()setclipboard("https://discord.gg/yWDJrpTjRP")end)m:addButton("Youtube Channel",function()setclipboard("https://www.youtube.com/channel/UCM3WvefUMUeiM-inCBcFlIA")end)m:addButton("Website",function()setclipboard("extremehub.xyz")end)n:addKeybind("Toggle Keybind",Enum.KeyCode.RightShift,function()print("Changed Keybind")i:toggle()end,function()end)n:addButton("Destroy UI",function()AutoFarmEnabled=false;AutoCollectOrbsEnabled=false;AutoCollectLootbagsEnabled=false;TripleCoinsEnabled=false;TripleDamageEnabled=false;UltraLuckyEnabled=false;SuperLuckyEnabled=false;AutoEquipBestEnabled=false;HatchingEnabled=false;ConvertGoldEnabled=false;ConvertRainbowEnabled=false;AutoCollectPetsEnabled=false;ClaimDarkMatterEnabled=false;EnchantingEnabled=false;FusingEnabled=false;RedeemGiftsEnabled=false;RedeemRankRewardsEnabled=false;RedeemVIPRewardsEnabled=false;BuyMerchantTier1Enabled=false;BuyMerchantTier2Enabled=false;BuyMerchantTier3Enabled=false;GetKickedIfStaffJoinsEnabled=false;local bj=game:GetService("CoreGui")["ExtremeHUB"]bj:Destroy()end)i:SelectPage(i.pages[1],true)

















































































































































































































--
